var toolboxLevel=[
    `
    <xml>
        <block type="move_forward"></block>
        <block type="turn_left"></block>
        <block type="turn_right"></block>
    </xml>
    `,
    `
    <xml>
        <block type="move_forward"></block>
        <block type="turn_left"></block>
        <block type="turn_right"></block>
        <block type="controls_repeat_ext">
            <value name="TIMES">
                <shadow type="math_number">
                    <field name="NUM">4</field>
                </shadow>
            </value>
        </block>
    </xml>
    `
]



var MissionInfo=[
    // 1
    {map:[  '                 ',
            '                 ',
            '                 ',
            '        |_       ',
            '        |        ',
            '                 ',
            '                 ',
            '                 ',
            '                 '],
    initPolice:{x:5,y:5,d:0},
    initThief:{x:5,y:7,d:0},
    level:0,
    hint:"想辦法用'前進'、'左轉'、'右轉'這些積木，把警車開去抓到小偷喔"
    },  
    {map:[  '                 ',
            '                 ',
            '                 ',
            '       _|_       ',
            '        |        ',
            '                 ',
            '                 ',
            '                 ',
            '                 '],
    initPolice:{x:5,y:5,d:0},
    initThief:{x:6,y:6,d:1},
    level:0,
    },
    {map:[  '                 ',
            '                 ',
            '         _       ',
            '         _|_     ',
            '        |        ',
            '                 ',
            '                 ',
            '                 ',
            '                 '],
    initPolice:{x:5,y:5,d:0},
    initThief:{x:5,y:7,d:3},
    level:0,
    },
    {map:[  '                 ',
            '                 ',
            '                 ',
            '                 ',
            '     _ _|        ',
            '    |            ',
            '                 ',
            '                 ',
            '                 '],
    initPolice:{x:5,y:5,d:0},
    initThief:{x:3,y:4,d:2},
    level:0,
    },
    {map:[  '                 ',
            '                 ',
            '                 ',
            '                 ',
            '     _ _         ',
            '        |        ',
            '        |_|_     ',
            '                 ',
            '                 '],
    initPolice:{x:5,y:5,d:0},
    initThief:{x:6,y:4,d:0},
    level:0,
    },
    {map:[  '         _ _ _ _ ',
            '        |        ',
            '        |        ',
            '        |        ',
            '        |        ',
            '                 ',
            '                 ',
            '                 ',
            '                 '],
    initPolice:{x:5,y:5,d:0},
    initThief:{x:9,y:9,d:1},
    level:0,
    }, 
    {map:[  '               _ ',
            '             _|  ',
            '           _|    ',
            '         _|      ',
            '       _|        ',
            '      |          ',
            '                 ',
            '                 ',
            '                 '],
    initPolice:{x:4,y:4,d:0},
    initThief:{x:9,y:9,d:1},
    level:0,
    },
    {map:[  '                 ',
            '                 ',
            '                 ',
            '                 ',
            '                 ',
            '       _|  _     ',
            '        |_| |    ',
            '                 ',
            '                 '],
    initPolice:{x:4,y:4,d:1},
    initThief:{x:7,y:3,d:2},
    level:0,
    },
    {map:[  '                 ',
            '                 ',
            '                 ',
            '                 ',
            '       _ _       ',
            '       _  |_     ',
            '        |_| |    ',
            '                 ',
            '                 '],
    initPolice:{x:4,y:4,d:1},
    initThief:{x:4,y:5,d:3},
    level:0,
    },
    {map:[  '                 ',
            '                 ',
            '                 ',
            '         _|_     ',
            '       _|  _|    ',
            '       _  |_     ',
            '        |_| |    ',
            '                 ',
            '                 '],
    initPolice:{x:4,y:4,d:1},
    initThief:{x:4,y:5,d:3},
    level:0,
    },
    {map:[  '                 ',
            '|                ',
            '|                ',
            '|                ',
            '|                ',
            '|                ',
            '|                ',
            '|                ',
            '|                '],
    initPolice:{x:1,y:1,d:0},
    initThief:{x:9,y:9,d:1},
    level:1,
    hint:"路程開始變長了，想辦法用'重複'積木減少使用的積木數"
    }, 
    {map:[  ' _ _ _ _ _ _ _ _ ',
            '|       |        ',
            '|       |        ',
            '|       |        ',
            '|       |        ',
            '|                ',
            '|                ',
            '|                ',
            '|                '],
    initPolice:{x:1,y:1,d:0},
    initThief:{x:9,y:9,d:1},
    level:1,
    }, 
    {map:[  ' _ _ _ _ _ _ _ _ ',
            '|       |       |',
            '|       |       |',
            '|       |       |',
            '|       |_ _ _ _|',
            '|               |',
            '|               |',
            '|               |',
            '|               |'],
    initPolice:{x:1,y:1,d:0},
    initThief:{x:9,y:1,d:2},
    level:1,
    }, 
    {map:[  '               _ ',
            '             _|  ',
            '           _|    ',
            '         _|      ',
            '       _|        ',
            '     _|          ',
            '   _|            ',
            ' _|              ',
            '|                '],
    initPolice:{x:1,y:1,d:0},
    initThief:{x:9,y:9,d:1},
    level:1,
    },
    {map:[  '               _ ',
            '             _| |',
            '           _|  _|',
            '         _|  _|  ',
            '       _|  _|    ',
            '     _|  _|      ',
            '   _|  _|        ',
            ' _|  _|          ',
            '|   |            '],
    initPolice:{x:1,y:1,d:0},
    initThief:{x:3,y:1,d:2},
    level:1,
    },
    {map:[  '                 ',
            '   _ _ _|        ',
            '  |_ _ _ _ _ _   ',
            '   _ _ _ _ _ _|  ',
            '  |_ _ _ _ _ _   ',
            '   _ _ _ _ _ _|  ',
            '  |_ _ _ _ _ _   ',
            '         _ _ _|  ',
            '        |        '],
    initPolice:{x:5,y:1,d:0},
    initThief:{x:5,y:9,d:0},
    level:1,
    },
    {map:[  '                 ',
            ' _   _   _   _   ',
            '| | | | | | | |  ',
            '| | | | | | | |  ',
            '| | | | | | | |  ',
            '| | | | | | | |  ',
            '| | | | | | | |  ',
            '| |_| |_| |_| |  ',
            '|             |  '],
    initPolice:{x:5,y:1,d:0},
    initThief:{x:5,y:9,d:0},
    level:1,
    }, 
    {map:[  '                 ',
            ' _   _   _ _ _ _ ',
            '| | | | |  _ _ _|',
            '| | | | | |_ _ _ ',
            '| | | | |  _ _ _|',
            '| | | | | |_ _ _ ',
            '| | | | |  _ _ _|',
            '| |_| |_| |_ _ _ ',
            '|               |'],
    initPolice:{x:1,y:1,d:0},
    initThief:{x:9,y:1,d:2},
    level:1,
    },
   
    {map:[  '                 ',
            '     _ _ _ _ _ _ ',
            '    |           |',
            '    |    _ _    |',
            '    |   |   |   |',
            '    |       |   |',
            '    |_ _ _ _|   |',
            '                |',
            ' _ _ _ _ _ _ _ _|'],
    initPolice:{x:5,y:5,d:0},
    initThief:{x:1,y:1,d:3},
    level:1,
    },
    {map:[  ' _ _ _ _ _ _ _ _ ',
            '|_|_|_|_|_|_|_|_|',
            '|_|_|_|_|_|_|_|_|',
            '|_|_|_|_|_|_|_|_|',
            '|_|_|_|_|_|_|_|_|',
            '|_|_|_|_|_|_|_|_|',
            '|_|_|_|_|_|_|_|_|',
            '|_|_|_|_|_|_|_|_|',
            '|_|_|_|_|_|_|_|_|'],
    initPolice:{x:5,y:5,d:0},
    initThief:{x:1,y:1,d:0},
    level:1,
    },
]